### PR TITLE
Add Nash market retrieval and expose market list across all exchange clients

### PR DESCRIPTION
**Pull request by Ejhfast**
* Added list markets request and implemented ExchangeInfoRetrieval via ExchangeInfo for Nash
* Provided market data to openlimits user by returning Vec<MarketPairHandle> when client calls refresh_market_info

### CODE REVIEW

**Comment by Ejhfast** [comment]
@acatinon if you have time, would love a quick sanity check on this! in particular on the second bullet point, so far as i could tell there was no existing way for openlimits user to actually retrieve and inspect the market list

(there are a few unsafe unwraps in there that should be cleaned up, but openlimits already has a number of those in a similar style. my plan is to add a new error type and clean up those + the ones already in the codebase using that)

**Comment by acatinon** [comment]
@Ejhfast You are right, the market list was not accessible to openLimits users. But maybe we should provide a way to retrieve the market list from the case without trigger a refresh each time ?

**Comment by Ejhfast** [comment]
If we pull the market data down, shouldn't we always update the market list? Otherwise there could be an inconsistency between what is presented to API user and what is kept by openlimits. I'm not 100% convinced on the current openlimits design (why it is storing this in the first place), but need to get something exposed for a Nash partner.

**Comment by Ejhfast** [comment]
I suppose we could add a trait method to just read from the current internal list with no network query, but that could also be confusing for users.

**Comment by acatinon** [comment]
I get your point, but calling `refresh_market_info()` to retrieve the market list is confusing too ;)

**Comment by acatinon** [comment]
Btw I agree, market data storage needs to be redesigned

**Review by acatinon — APPROVED** [review]

**Comment by Ejhfast** [comment]
Thanks @acatinon, I will just merge this for now and open an issue to rethink market info storage and retrieval.

**Pull request merged**
