### PR TITLE
Binance websocket respond to ping

### PR DESCRIPTION
**Pull request by fabianboesiger**

### CODE REVIEW

**Comment by steffenix** [comment]
Why did you closed your PR?

**Comment by fabianboesiger** [comment]
I tested the changes by running a websocket stream on my server for some time and the disconnects continued to happen, so I assumed there is something wrong with my proposed solution.

But although the disconnects still happen, they do so less frequently. I'm not sure why they still happen.

**Comment by acatinon** [comment]
I had a look at the [tungstenite source code](https://docs.rs/tungstenite/0.11.1/src/tungstenite/protocol/mod.rs.html#161):

> Note that upon receiving a ping message, tungstenite cues a pong reply automatically. When you call either `read_message`, `write_message` or `write_pending` next it will try to send that pong out if the underlying connection can take more data. This means you should not respond to ping frames manually.

So it seems tungstenite handle pong reply when receiving a ping automatically. To be sure, I added traces on a openLimits Binance websoket test. There an extract:

```
[2020-09-12T10:07:35Z TRACE tungstenite::protocol::frame::frame] Parsed headers [137, 13]
[2020-09-12T10:07:35Z TRACE tungstenite::protocol::frame::frame] First: 10001001
[2020-09-12T10:07:35Z TRACE tungstenite::protocol::frame::frame] Second: 1101
[2020-09-12T10:07:35Z TRACE tungstenite::protocol::frame::frame] Opcode: Control(Ping)
[2020-09-12T10:07:35Z TRACE tungstenite::protocol::frame::frame] Masked: false
[2020-09-12T10:07:35Z TRACE tungstenite::protocol::frame] received frame 
    <FRAME>
    final: true
    reserved: false false false
    opcode: PING
    length: 15
    payload length: 13
    payload: 0x31353939393035323535373738
                
[2020-09-12T10:07:35Z TRACE tungstenite::protocol] Received message 1599905255778
[2020-09-12T10:07:35Z TRACE tungstenite::protocol] Sending pong reply
[2020-09-12T10:07:35Z TRACE tungstenite::protocol] Sending frame: Frame { header: FrameHeader { is_final: true, rsv1: false, rsv2: false, rsv3: false, opcode: Control(Pong), mask: Some([166, 155, 220, 144]) }, payload: [49, 53, 57, 57, 57, 48, 53, 50, 53, 53, 55, 55, 56] }
[2020-09-12T10:07:35Z TRACE tungstenite::protocol::frame] writing frame 
    <FRAME>
    final: true
    reserved: false false false
    opcode: PONG
    length: 19
    payload length: 13
    payload: 0x31353939393035323535373738
```

We can see we receive a PING and write a PONG immediately after. So I guess the disconnections you have are not connected to ping...

There is the code I used to see the traces (using `env_logger` crate): 

```Rust
    let _ = env_logger::builder()
        .filter_module("tungstenite::protocol", LevelFilter::Trace)
        .is_test(true)
        .try_init();

    let mut websocket = BinanceWebsocket::new();
    let sub = Subscription::OrderBook("bnbbtc".to_string(), 5);

    websocket.subscribe(sub).await.unwrap();

    for _ in 1..1000 {
        let _ = websocket.next().await;
    }
```

**Comment by steffenix** [comment]
Thanks @acatinon

**Pull request closed without merging**
