### PR TITLE
Exchange trait refactoring

### PR DESCRIPTION
**Pull request by acatinon**
* Split `Exchange` trait into:
  * `ExchangeEssentials` to uniformize exchange instantiation with `ExchangeParameters` and `ExchangeId`, allowing to easily retrieve `Exchange` instance metadata (sandbox or not, credentials...)
  * `ExchangeSpec` to centralize `OrderId`, `TradeId` and `Pagination` types in one place
  * `ExchangeMarketData` and `ExchangeAccount` to allow partial implementations if needed
* Rename `OpenLimits` to `Exchange`
* Allow access to exchanges concrete implementations if needed with `Exchange` `inner` field in order to address [dovahcrow concern](https://openlimitsworkspace.slack.com/archives/C0162G95ZJR/p1593669316022000) about the need to provide thin layer on each exchange API

Uniformized exchange parameters and ids should also be useful in the future if openLimits users want to merge websocket streams for 2 exchanges or maybe 2 accounts from the same exchange...

### CODE REVIEW

**Comment by Ejhfast** [comment]
Thanks for pushing on this @acatinon! Really like the idea, and particularly standardizing the initialization stuff will be super useful even in the short term -- something like that is required to make the python wrapper sanely support all openlimits exchanges, as opposed to just Nash. Will take a cloer look soon.

**Comment by Ejhfast** [comment]
One big change I'd like to make (and just pushed here) is to remove all the associated types for ids and pages. It creates a big downstream hassle for consumer code that processes responses from any openlimits compatible exchange. We can just to the conversion to and from strings inside the client bindings for coinbase, binance, etc.

**Comment by Ejhfast** [comment]
This turned into a pretty huge refactor, but I'm pretty happy with how the traits in `exchange.rs` are looking now. Still would like to fix up the websockets traits a bit

**Comment by Ejhfast** [comment]
I still don't love the WS traits, but it is more work than I'm willing to deal with at the moment to fix that in this branch. For now just added uniform instantiation as we had for the `Exchange` trait. Want to get this into master, then can continue improvements through smaller PRs.

**Comment by Ejhfast** [comment]
I think the current meets your original goals @acatinon with a few simplifications on the traits. I'm going to merge this now as other things are blocking on it, but will leave the branch and PR open if you have other suggestions

**Comment by acatinon** [comment]
thanks @Ejhfast, I will have a look at your commits. Btw I have a stash about WebSockets too, I will try to add it tonight

**Pull request merged**
