### PR TITLE
Disable incompatible code on wasm32

### PR DESCRIPTION
**Pull request by mankinskin**
This makes the crate as least be compiled for wasm32 and allows you to
use the types in the model module for web APIs and stuff

### CODE REVIEW

**Comment by steffenix** [comment]
How are the websockets working without tokio?

**Comment by mankinskin** [comment]
> How are the websockets working without tokio on wasm?

They are not working. This disables basically anything that needs to be run in this crate. It is only useful to build it on wasm so that can use the data types in the model module. I am using it for my server/client api to serialize and deserialize data.

**Comment by steffenix** [comment]
Binance and Coinbase APIs re using sockets so I think there is more to disable here, plus I am planning to add the websocket support to openlimits, currently still WIP (looking for help on how to manipulate Stream), I will hold on this PR for now.

**Comment by mankinskin** [comment]
full wasm compatibility is probably something that requires more work. I know of the [seed framework](https://github.com/seed-rs/seed), which targets wasm client apps and provides [web sockets](https://docs.rs/seed/0.7.0/seed/browser/web_socket/struct.WebSocket.html), possibly this could be used to port this library to the browser some time. This PR would only allow the crate to compile for wasm32, at least.

**Comment by notdanilo** [comment]
There is an ongoing effort to implement a cross-platform WebSocket which means that this issue can get solved at some point soon if we decide to rework the current clients.

**Comment by notdanilo** [comment]
This PR just disables the tokio runtime and won't make the library work in wasm.

**Pull request closed without merging**
